### ISSUE TITLE
better usability around optionals

### ISSUE THREAD

**Issue by abraithwaite** [segmentio/cli#6]
~As the package currently stands, you can't have empty optional string arguments.  This is desirable for a common scenario like overriding arguments which if unset would be determined through third party means.  That is to say, you can't set it to a default if the configuration is to come from outside the program.~

~In our case, we query a database for a path parameter that we want to be able to override in the cli.  In order to do that now, you have to set a default to some known-but-unlikely value like `default"unset"` for strings, but that's really less desirable than just allowing blank optional parameters.~

**Comment by achille-roussel** [comment]
I believe the behavior you describe is supported by `default:"-"`, which sets the option to its zero-value.

Let me know if that helps.

**Comment by abraithwaite** [comment]
Ah, I missed that in the docs.  That does what I want yeah.  

I wonder if there's a more clear API here.  I guess it's better to err on the side of requiring flags without defaults over not having a special character or string.
